### PR TITLE
Add Shinnok as java

### PR DESCRIPTION
**Pull request by matthewbcool**

### CODE REVIEW

**Comment by matthewbcool** [comment]
Still going, brb

**Comment by jreina** [comment]
this is awesome 🤘🤘🤘

**Comment by jreina** [comment]
@matthewbcool were you still planning to get this PR in? I was really looking forward to having a more complete set of icons on this pack.

**Comment by matthewbcool** [comment]
@jreina  For sure! I think @Pslice  has the most complete set ATM. Maybe he can make a new PR

**Review by Pslice — COMMENTED** [review]
cool, how do I add that change? is it locked because its closed?

**Comment by jreina** [comment]
I think you need to create another PR. It shows that the repo for this PR no longer exists. Was the fork made private?

**Pull request closed without merging**
